### ISSUE TITLE
 Could not render your request

### ISSUE THREAD

**Issue by BlakeB415** [surgeplay/Visage#10]
When I go to the url https://visage.surgeplay.com/face/512/958b092733d14b6c87a98dc9e8c67358 I get this .

HTTP ERROR: 500

Problem accessing /face/512/958b092733d14b6c87a98dc9e8c67358. Reason:

    Could not render your request
Powered by Jetty:// 9.3.0.RC0

**Comment by exaskye** [comment]
Resolved, the slave was down. I know this has been happening a lot lately but there's not a whole lot I can do at the moment.

**Comment by leMaik** [comment]
@unascribed We would like to help out with rendering again, but we changed our server and unfortunately, the new one doesn't have a GPU. :cry:
