### ISSUE TITLE
LWJGL not in classpath

### ISSUE THREAD

**Issue by RobertHerhold** [surgeplay/Visage#15]
When running the [1.3.1 release](https://github.com/surgeplay/Visage/releases/tag/v1.3.1) as a slave:

```
@15:53:16.380           Main thread  INFO: Starting Visage v1.3.1 as a slave
@15:53:16.607           Main thread  INFO: Slave name is '55c4ee1bdac1'
@15:53:16.612           Main thread  INFO: Press Ctrl+C to shutdown Visage.
@15:53:16.616          Slave thread  INFO: Setting up LWJGL
Exception in thread "Slave thread" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1889)
at java.lang.Runtime.loadLibrary0(Runtime.java:849)
at java.lang.System.loadLibrary(System.java:1088)
at org.lwjgl.Sys$1.run(Sys.java:72)
at java.security.AccessController.doPrivileged(Native Method)
at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
at org.lwjgl.Sys.loadLibrary(Sys.java:87)
at org.lwjgl.Sys.<clinit>(Sys.java:117)
at org.lwjgl.opengl.Pbuffer.<clinit>(Pbuffer.java:148)
at com.surgeplay.visage.slave.VisageSlave.run(VisageSlave.java:92)
```

**Comment by exaskye** [comment]
Are you using the run.sh or run.bat?

**Comment by RobertHerhold** [comment]
run.sh

**Comment by exaskye** [comment]
Okay, I thought you may have been running it as `java -jar` directly, hence the question. (Realized it's not entirely clear)

What operating system? I've only tested this on Linux, not Unix or macOS.

**Comment by RobertHerhold** [comment]
I get the same error on both macOS and Ubuntu 16.04

**Comment by exaskye** [comment]
Does your lib/natives directory have a `liblwjgl64.so` and a `liblwjgl64.dylib`?

**Comment by RobertHerhold** [comment]
No... I don't see either of those in the zip from the releases page either though

**Comment by RobertHerhold** [comment]
I tried building it w/ Gradle to see if a build I ran was any different, and got this error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/robert/projects/Visage/build.gradle' line: 8

* What went wrong:
An exception occurred applying plugin request [id: 'com.stehno.natives', version: '0.2.4']
> Failed to apply plugin [id 'com.stehno.natives']
   > Could not create task of type 'UnpackNativesTask'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by exaskye** [comment]
Yeah, I don't have a liblwjgl64.dylib either, but I do have a .so.

What happens if you rename liblwjgl.dylib to liblwjgl64.dylib? (This may sound really dumb, I have no idea how macOS libraries work, but file claims it's a "universal" binary with 64-bit capability)

I don't think the project builds on new versions of Gradle. I need to update it.

**Comment by RobertHerhold** [comment]
I don't seem to have any `liblwjgl.*`... only `lwjgl-*`. Here is what I have in the lib directory:

```
Visage-1.3.1-SNAPSHOT.jar
amqp-client-3.5.1.jar
commons-pool2-2.0.jar
config-1.2.1.jar
gson-2.2.4.jar
guava-18.0.jar
jansi-1.11.jar
javapng-2.1.2.jar
javax.servlet-api-3.1.0.jar
jedis-2.6.2.jar
jetty-http-9.3.0.RC0.jar
jetty-io-9.3.0.RC0.jar
jetty-server-9.3.0.RC0.jar
jetty-util-9.3.0.RC0.jar
jinput-2.0.5.jar
jinput-platform-2.0.5-natives-linux.jar
jinput-platform-2.0.5-natives-osx.jar
jinput-platform-2.0.5-natives-windows.jar
jopt-simple-4.5.jar
jutils-1.0.0.jar
lwjgl-2.9.3.jar
lwjgl-platform-2.9.3-natives-linux.jar
lwjgl-platform-2.9.3-natives-osx.jar
lwjgl-platform-2.9.3-natives-windows.jar
lwjgl_util-2.9.3.jar
mcauthlib-1.0-SNAPSHOT.jar
natives
token-bucket-1.6.jar
```

EDIT: I see there is one each for Linux, OSX, and Win... is it just a file name discrepancy?

**Comment by exaskye** [comment]
lib/*natives*, not just lib.

```
$ ls -l lib/natives/
total 4616
-rw-r--r-- 1 aesen users  65024 Jul 22  2016 jinput-dx8_64.dll
-rw-r--r-- 1 aesen users  61952 Jul 22  2016 jinput-dx8.dll
-rw-r--r-- 1 aesen users  62464 Jul 22  2016 jinput-raw_64.dll
-rw-r--r-- 1 aesen users  59392 Jul 22  2016 jinput-raw.dll
-rw-r--r-- 1 aesen users  56832 Jul 22  2016 jinput-wintab.dll
-rw-r--r-- 1 aesen users  14512 Jul 22  2016 libjinput-linux64.so
-rw-r--r-- 1 aesen users  13656 Jul 22  2016 libjinput-linux.so
-rw-r--r-- 1 aesen users  64608 Jul 22  2016 libjinput-osx.jnilib
-rw-r--r-- 1 aesen users 469936 Jul 22  2016 liblwjgl64.so
-rw-r--r-- 1 aesen users 531120 Jul 22  2016 liblwjgl.dylib
-rw-r--r-- 1 aesen users 395108 Jul 22  2016 liblwjgl.so
-rw-r--r-- 1 aesen users 404085 Jul 22  2016 libopenal64.so
-rw-r--r-- 1 aesen users 368392 Jul 22  2016 libopenal.so
-rw-r--r-- 1 aesen users 317440 Jul 22  2016 lwjgl64.dll
-rw-r--r-- 1 aesen users 306176 Jul 22  2016 lwjgl.dll
-rw-r--r-- 1 aesen users 390144 Jul 22  2016 OpenAL32.dll
-rw-r--r-- 1 aesen users 382464 Jul 22  2016 OpenAL64.dll
-rw-r--r-- 1 aesen users 731648 Jul 22  2016 openal.dylib
```

**Comment by RobertHerhold** [comment]
*facepalm* sorry. I have all the files you mentioned:

```
liblwjgl.dylib
liblwjgl.so
liblwjgl64.so
```

**Comment by exaskye** [comment]
Also, the service keeps going down because I don't have many slaves and the GPU in my server is borked. I spent a  few hours trying to get X to work properly on the server yesterday and didn't get it quite working, so if after this is fixed you want to join the official slave pool I can give you the credentials.

----

Okay, as suggested, rename `liblwjgl.dylib` to `liblwjgl64.dylib`.

**Comment by RobertHerhold** [comment]
Renamed and the same issue persists

**Comment by exaskye** [comment]
Um... `grep 'library' bin/Visage`?

**Comment by RobertHerhold** [comment]
```
DEFAULT_JVM_OPTS='"-Djava.library.path=./lib/natives/"'
```

Ahh one sec, let me try something

**Comment by RobertHerhold** [comment]
I was running Visage from a different working directory, so that relative path screwed it up. It's fixed now.

Thanks :)

**Comment by RobertHerhold** [comment]
@unascribed I've been trying to get a simple Docker image of Visage working, and I got stuck at this point:

```
Exception in thread "Slave thread" java.lang.ExceptionInInitializerError
at org.lwjgl.opengl.Pbuffer.createPbuffer(Pbuffer.java:234)
at org.lwjgl.opengl.Pbuffer.<init>(Pbuffer.java:219)
at com.surgeplay.visage.slave.VisageSlave.run(VisageSlave.java:92)
Caused by: java.lang.RuntimeException: org.lwjgl.LWJGLException: Could not open X display connection
at org.lwjgl.opengl.Display.<clinit>(Display.java:141)
... 3 more
```

After that, I tried `apt-get install`ing `xorg` and `openbox`, but got stuck where it asks for keyboard configuration... Is this the same issue you're having with X, or a different one?

**Comment by exaskye** [comment]
It's fairly similar - Visage *requires* direct rendering and OpenGL to operate. The only way to get it to work is to be on baremetal with a GPU, or a VM with VGA passthru. I'm on the former and getting it to work with no display attached is an ordeal to say the least.

It was designed for running on my home server, which has a GPU and is headed with a reliable internet connection. It doesn't have a reliable internet connection anymore as I'm in the middle of moving.
