### ISSUE TITLE
Blank images

### ISSUE THREAD

**Issue by shane-smith** [surgeplay/Visage#16]
I've started using Visage on a local test site for my Minecraft server. Essentially, I plan to get the initial image from Visage and to then cache permanently until the user invalidates their own cache manually (e.g. because they've had a skin update), thereby impacting on your traffic as little as possible.

However, I'm facing the problem that Visage is spitting out blank images **more than 50%** of the time, and **seemingly at random**. The 'bust' will work for one player, but the 'face' will not. Another player might have 'face' or 'head' working, but not 'bust'.

It's also broken on the Visage page! https://visage.surgeplay.com/ - see the screenshot I've included below.

The image returned is the correct dimensions but every pixel is transparent. So to a web application there is no easy way to tell if it was successful, but to a human viewing the images it's quite clear something is wrong.

Same result whether using UUID or username.

Thanks.

<img width="1132" alt="screen shot 2017-02-08 at 12 32 46 am" src="https://cloud.githubusercontent.com/assets/943942/22694340/c5b642d4-ed96-11e6-9792-5d057b80fb2f.png">

**Comment by exaskye** [comment]
This is a known issue with the nVidia proprietary driver, since I use legacy GL. Visage is pending a major refactor to update it to modern GL.

**Comment by exaskye** [comment]
Oh, you're setting up a caching proxy. Sorry, I thought you were running your own server.

I have my own quite aggressive cache, you don't need to run your own.

There's a slave in the pool running the nVidia proprietary driver, which, as said, is known to be broken. I'm talking to the owner of it to try to find a solution.

EDIT: It should be fixed for now, I've kicked off the slave.

**Comment by shane-smith** [comment]
Thanks @unascribed - can confirm that it's working this morning! :D Very fast response.

If it happens again (as you mentioned that you're only able to do a temporary fix for now), I'll let you know. Appreciate your help, the 3D images from Visage are awesome.
