### ISSUE TITLE
Tried installing Visage on my Dedi :(

### ISSUE THREAD

**Issue by TNTUP** [surgeplay/Visage#17]
Hi, I've tried installing the dependcies but when I launch it, I get the X display error. The server is hosted at OVH and has no GPU, tried enabling the slave and software rendering, no luck.

Tried solving the X display error by entering commands but nothing again =(

Is there any tips to get it working on machines which does not have a GPU?

**Comment by exaskye** [comment]
Visage does not run on boxes with no GPUs, period. Sorry.

**Comment by TNTUP** [comment]
Ah dang :/ thanks for your fast answer^^
