### ISSUE TITLE
Server HTTP response 500

### ISSUE THREAD

**Issue by sannielollie** [surgeplay/Visage#19]
Since about 3-4 days im getting a HTTP error 500 when fetching a skin through the API, i dont know what is going on, looks like something with the visage server.

HTTP ERROR: 500

Problem accessing /head/d5cdaf3d3c8f4b7b97ce324f222e1ef6. Reason:

    Could not render your request

This shows up in my logfile (using ServerListPlus on bungeecord) : https://pastebin.com/eb1veEKh

**Comment by Snuggle** [comment]
I am also experiencing these errors. http://i.imgur.com/Ik5f4KO.png

**Comment by exaskye** [comment]
The slave exploded. Restarted.

Lasted a few months that time, pretty happy.

**Comment by sannielollie** [comment]
Again getting errorcode 500     Could not render your request
 since a few days

**Comment by Snuggle** [comment]
@unascribed I can confirm.

Needing to use a fallback while you're down.

**Comment by Snuggle** [comment]
Is there any way you can auto-restart it? I'm not sure what the issue is.

**Comment by exaskye** [comment]
...since a few days? Can you try to notify me more quickly? >.>

Should work again.

Been really busy lately, haven't been able to monitor Visage.

EDIT: The issue is an obscure bug with my OpenGL renderer, which is overdue for a rewrite. I haven't had time to do said rewrite, though.

**Comment by sannielollie** [comment]
I was waiting maybe it would restart automatically - will tell more soon if it happens again :P thanks for solving!
