### ISSUE TITLE
Missing Transparency handle

### ISSUE THREAD

**Issue by tobimori** [surgeplay/Visage#20]
If i have an transparent skin, minecraft renders it as black.
Visage renders it as transparent. (Skin: EinCommandBlock)

**Comment by exaskye** [comment]
Ugh. I don't even know how Minecraft does this, and I had a hack to try to mitigate this; guess it doesn't work.

**Comment by exaskye** [comment]
Nevermind, apparently this isn't fixed. I was told what I did would work, it doesn't. -.-
