### ISSUE TITLE
Choppy, over-sized renders.

### ISSUE THREAD

**Issue by Qetah** [surgeplay/Visage#27]
Recently, Visage renders on my site (pulled directly from visage.surgeplay.com rather than self-hosted) have displayed as larger than normal, with previously smooth borders around the render becoming more pixelated and choppy, with a seeming black border. See below for a before/after comparison of the 512*512px bust render:
![qetahrender](https://user-images.githubusercontent.com/19560981/28853488-7a5ece0c-76f6-11e7-8255-c3ff087dcedb.png)
![brokenexample](https://user-images.githubusercontent.com/19560981/28853523-bddbf61e-76f6-11e7-93f3-08122b5d0765.png)
Is this intentional? If so, is there a way to revert it? Thanks.

**Comment by exaskye** [comment]
The render being larger is intentional to make better use of the space. The choppy antialiasing is #25 -  the fix for that issue isn't working in production and I haven't had time to look into it. (I do now.)

**Comment by Qetah** [comment]
Fantastic, thanks for the quick response.
