### ISSUE TITLE
Notch's skin has an opaque helmet

### ISSUE THREAD

**Issue by DoubleParallax** [surgeplay/Visage#28]
https://visage.surgeplay.com/head/512/069a79f444e94726a5befca90e38aaf5

Skin texture isn't transparent for the helmet, but renders fine for every other service using the skin texture data from Mojang

**Comment by exaskye** [comment]
Oh, right. When I rewrote the skin handling code I forgot to keep the compatibility with Notch's broken skin.

I don't really think I care, though.

**Comment by exaskye** [comment]
This is not worth the code complication and work on my end to support, considering it only affects one skin, and you can use MHF_Notch for a skin that isn't broken. (Note that MHF_Notch is not an official MHF skin and is controlled by another user, and so it may change without notice. I may hardcode a fixed Notch skin to "fix" this issue, as that is considerably less effort than supporting this incredibly rare weirdly broken skin.)
