### ISSUE TITLE
Option for antialiasing

### ISSUE THREAD

**Issue by NickUfer** [surgeplay/Visage#29]
Hello,
first of all, I appreciate your hard work and I'm very thankful for your renderer :+1: 
But I wanted to ask if there's any possibility for antialiasing and if there's no option, I wanted to ask you if you please could add such an option^^ That would be amazing^^

Have a nice day,
DerTechNick

**Comment by exaskye** [comment]
What? Are you asking to be able to disable antialiasing?

**Comment by NickUfer** [comment]
No, but I think there is no antialiasing when I render skins :sweat_smile:

**Comment by exaskye** [comment]
![image](https://user-images.githubusercontent.com/6185037/29988832-475f6af2-8f3d-11e7-81fc-12359fe421e4.png)
There is antialiasing.

**Comment by exaskye** [comment]
What you are probably seeing is the black haloing that I haven't had time to fix.

**Comment by NickUfer** [comment]
ah okay :)
