### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by zTryhqrd** [surgeplay/Visage#3]
Hello, I updated my skin like 3 days ago and the render got updated now.. But it is taking way too long? Is there any way how you guys can fix that? Like the cache stuff..?

**Comment by exaskye** [comment]
What URL seems to be out-of-date? Best I can tell, the cache is in-sync.

**Comment by zTryhqrd** [comment]
https://visage.surgeplay.com/full/512/e07e2db74c474230ab62334ead237c4c
But its not only for my skin, it takes very long to update etc.

**Comment by exaskye** [comment]
I've reduced cache times to 8 hours on the edge, and 8 days in the browser. Skins should update fairly quickly as a result now.
