### ISSUE TITLE
Does not render 3 pixel arm "alex" skin

### ISSUE THREAD

**Issue by Trimbell** [surgeplay/Visage#6]
Whenever you try to render 3 pixel arm "alex" skins, it renders them like steve. Try it on my skin, which is an alex skin, and you will see that it renders it like steve. Since it might not be able to auto detect alex or steve, what it could do is add /alex parameter thing to the end of the url

**Comment by exaskye** [comment]
Oh, right. I added everything required to implement this, and then forgot to actually hook it up by checking if the account has an Alex skin. Good job me.

I'm a bit busy at the moment and won't be able to fix this for a while.

**Comment by Trimbell** [comment]
Alright
Also it would be nice to be able to force it to render in either steve or alex mode, possibly by doing /steve or /alex
