### ISSUE TITLE
Dinnerbone's head is upside down

### ISSUE THREAD

**Issue by Gaelan** [surgeplay/Visage#8]
or right side up, or whatever. It should be rotated the other way so that it matches his in-game appearance. Not a super big issue, but would be a nice Easter egg/hidden feature that makes someone's day.

**Comment by exaskye** [comment]
I've been asked to do this a few times, and probably will next time I work on Visage.

**Comment by exaskye** [comment]
![image](https://user-images.githubusercontent.com/6185037/28002092-d667f222-64ff-11e7-8a69-a80d01bce200.png)
![image](https://user-images.githubusercontent.com/6185037/28002094-da996448-64ff-11e7-901f-e571f7b2649e.png)
I hope this is acceptable. :P
