### ISSUE TITLE
White margin around Face renderer

### ISSUE THREAD

**Issue by Semx11** [surgeplay/Visage#9]
When using the Face renderer, there is a 1 pixel white margin around the skin. I know that it reserves some whitespace if the skin has a 2nd layer on the outsides of the front head, but even then it has excessive whitespace.
A possible workaround for this is to have an option so it doesn't render the 2nd layer further away from the 1st layer, so all whitespace can be removed.

**Comment by chickenputty** [comment]
I agree, this is one of the major issues.

**Comment by exaskye** [comment]
Upon further inspection, there *is* an unintentional border, beyond the 2nd skin layer.

Wouldn't have noticed if I didn't add the new debug functionality to 2.0.0. :P
